name: rag-chatbot
description: RAG chatbot
tags:
  - RAG
  - LLM
resources:
  cluster: snu-eng-dgx
  preset: a100-1
image: PyTorch 2.3.1 (CUDA 12.1)  # quay.io/vessl-ai/torch:2.3.1-cuda12.1-r5
import:
  /code/:
    git:
      url: https://github.com/pikaybh/RAG-vllm-RA.git
  /certs/:
    local: ./certs  # SSL 인증서가 있는 로컬 경로
run:
  - command: |  # Install some dependencies for LLM acceleration those have conflicts with common libraries
      apt update && apt install -y libgl1
      pip install autoawq>=0.2.6
      pip install vllm>=0.6.3
      pip install flash-attn>=2.6.3
    workdir: /code
  - command: |
      vllm serve $MODEL_NAME --dtype auto --gpu-memory-utilization 0.8 &
    workdir: /code
  - command: |
      pip install -r requirements.txt
    workdir: /code
  - command: |
      python app.py --llm-host http://localhost:8000/v1
    workdir: /code
ports:
  - name: gradio
    type: https
    port: 7860
  - name: vllm
    type: http
    port: 8000
service:
  autoscaling:
    max: 2
    metric: cpu
    min: 1
    target: 50
  monitoring:
    - port: 5000
      path: /metrics
  expose: 8000
env:
  MODEL_NAME: casperhansen/llama-3-8b-instruct-awq
